[package]
name = "fleet-renderer"
version = "0.1.0"
authors = ["Ashley Ruglys <ashley.ruglys@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
bytemuck = { version = "1.5.1", features = ["derive"] }
gltf = { version = "0.15.2", features = ["utils"], default-features = false }
image = { version = "0.23.14", features = ["png"], default-features = false }
pollster = "0.2.3"
ultraviolet = { version = "0.8.0", features = ["bytemuck"] }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs" }
winit = "0.24.0"
web-sys = { version = "0.3.50", optional = true }
# Background
spade = "1.8.2"
tint = "1.0.1"
noise = "0.7.0"
rand = "0.8.3"
env_logger = "0.8.3"

# Compile all dependencies in release mode
[profile.dev.package."*"]
opt-level = 3

[patch."https://github.com/gfx-rs/wgpu"]
wgpu-core = { git = "https://github.com/expenses/wgpu", branch = "texture-size-query-flags" }
wgpu-types = { git = "https://github.com/expenses/wgpu", branch = "texture-size-query-flags" }
