[package]
name = "fleet-renderer"
version = "0.1.0"
authors = ["Ashley Ruglys <ashley.ruglys@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
bytemuck = { version = "1.5.1", features = ["derive"] }
gltf = { version = "0.15.2", features = ["utils"], default-features = false }
image = { version = "0.23.14", features = ["png"], default-features = false }
pollster = "0.2.4"
ultraviolet = { version = "0.8.0", features = ["bytemuck"] }
wgpu = { version = "0.8.0", features = ["cross"] }
winit = "0.24.0"
web-sys = { version = "0.3.50", optional = true }
# Background
spade = "1.8.2"
tint = "1.0.1"
noise = "0.7.0"
rand = "0.8.3"
env_logger = "0.8.3"
legion = { version = "0.4.0", default-features = false, features = ["codegen"] }
rstar = { git = "https://github.com/expenses/rstar", branch = "selection-function-with-data" }

[features]
default = ["parallel"]
parallel = ["legion/parallel"]

# Compile all dependencies in release mode
[profile.dev.package."*"]
opt-level = 3
