[package]
name = "systems"
version = "0.1.0"
authors = ["Ashley Ruglys <ashley.ruglys@gmail.com>"]
edition = "2018"

[dependencies]
bevy_ecs = "0.5.0"
bytemuck = "1.5.1"
components-and-resources = { path = "../components-and-resources/" }
ultraviolet = "0.8.1"
